Update Github Workflow: Lint Code Base
Updated Github Action checkout from v3 to v6.

Updated Github Action setup-linter from v5 to v8.

Updated the workflow as described in the "Get started" example, see:
https://github.com/super-linter/super-linter/blob/main/README.md#get-started

Disable BASH_EXEC linter, because else it fails on files/ansible_facts.d/services.fact:

  BASH_EXEC
    Error: -21 11:54:05 [ERROR]   Errors found in BASH_EXEC
    Error: -21 11:54:05 [ERROR]   Stdout contents for BASH_EXEC:
    ------
    Error: File:[/github/workspace/files/ansible_facts.d/services.fact] is not executable
    ------

Add permissions in .github/workflows/molecule.yml, else CHECKOV fails:

  CHECKOV
    Error: -21 11:54:06 [ERROR]   Errors found in CHECKOV
    Error: -21 11:54:06 [ERROR]   Stdout contents for CHECKOV:
    ------
    github_actions scan results:

    Passed checks: 79, Failed checks: 1, Skipped checks: 0

    Check: CKV2_GHA_1: "Ensure top-level permissions are not set to write-all"
          FAILED for resource: on(Ansible Molecule Workflow)
          File: /.github/workflows/molecule.yml:0-1
    ansible scan results:

    Passed checks: 14, Failed checks: 0, Skipped checks: 0
    ------

persist-credentials: false is needed, else GITHUB_ACTIONS_ZIZMOR fails.

Closes: #31